version: '2'
services:
  notes-db:
    image: "mikaelsouza/notes-db:0.0.1"
    container_name: notes-db
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=notes
      - MYSQL_PASS=notes
      - MYSQL_DATABASE=db


