
version: '2'
services:
  notes-db:
    image: "mikaelsouza/notes-db:0.0.1"
    container_name: notes-db
    environment:
      - MYSQL_ROOT_PASSWORD=notes
      - MYSQL_PASS=notes
      - MYSQL_DATABASE=db
    volumes:
      - my-datavolume:/var/lib/mysql
  notes-backend:
    image: "mikaelsouza/notes-backend:port50002"
    container_name: notes-backend
    ports:
      - '50002:50002'
    environment:
      - DB_HOST=notes-db
  notes-frontend:
    image: mikaelsouza/notes-frontend:port50001
    container_name: notes-frontend
    ports:
      - '50001:50001'
volumes:
  my-datavolume: